# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [3]:
'''
np.zeros((2,3))會產生真正的0;np.empty((2,3))會產生一個近似於0的陣列。
np.empty可以用於只是想要初始化，但之後就會數值副寫過的情況。
'''

'\nYour Code\n'

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [9]:
# 記得先 Import 正確的套件
import numpy as np

a = np.random.rand(2, 3)
a = a*100

print(a)

[[28.94175599 86.35456798 72.42931747]
 [75.01965189 61.57649188 90.56275713]]


In [8]:
# 參考解答

print(a.round())
print(np.round(a))
      

[[84. 60. 86.]
 [94. 90. 13.]]
[[84. 60. 86.]
 [94. 90. 13.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [17]:
m = 20
n = 40

a = np.random.rand(2,3)*(n-m)
b = a
print((a-b%1)+m)

[[30. 33. 29.]
 [35. 33. 39.]]
