# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [ ]:

#sum()是Python內建的函式，所有型態皆可以用。np.sum(a)與a.sum()是陣列專有的函式，差別在於定義在np或是array底下。

'\nYour Code\n'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [1]:
# 記得先 Import 正確的套件

import numpy as np

In [4]:
A = np.random.random((5, 5))
A = (A-A.min())/(A.max()-A.min())

print(A)

[[0.14407168 0.72984926 0.         0.5908531  0.89572621]
 [0.33713057 0.23954956 0.12547796 0.19889079 0.30988798]
 [0.02656912 0.82883939 0.34599831 0.12301486 0.80938753]
 [0.93482666 0.25778527 0.4073184  0.97716735 0.23411843]
 [0.34765627 0.61625892 1.         0.58997771 0.60484622]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [12]:
Z = np.random.random(10)
Z[Z.argmax()] = -1
print(Z)

[ 0.1474232   0.5156727   0.68848108  0.3316047   0.55523243  0.25398122
  0.5383122  -1.          0.88943851  0.62750748]
